export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_START:"categoy/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCESS:"categoy/FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILED:"categoy/FETCH_CATEGORIES_FAILED",
  };
  